# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8751af4dcefa34cfd18e61ce2b9582d35b630778478fc13822b6b31df648daf6f2068324ee56b75d3f1e0dde2be0c533ec8c0b8223213bab73903d049342ee2d

test:
  secret_key_base: dac43b4bc7ed6045c494189bad9cad2c1725aa2646f9d7539183b1a1d6d678fdddc952ef54a74f857478adac8e1aaf9a4ce4a05df4eb432376c88bc4454700cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
